#ifndef HEAPEXCEPTION_H
#define HEAPEXCEPTION_H

/*******************************
 * DO NOT EDIT THIS FILE
 *******************************/

/*
 * All exceptions are derived from the 'exception' class
 *  - consequently, catch( excpetion ) { ... } will catch only these exceptions
 *
 *       HeapException <----- underflow
 *                    |-- underflow
 *                    |-- overflow
 *                    |-- division_by_zero
 *                    |-- illegal_argument
 *                     -- out_of_range
 */

class HeapException {
	// empty class
};

class HeapUnderflow : public HeapException {
	// empty class
};

class HeapOverflow : public HeapException {
	// empty class
};

class HeapDivisionByZero : public HeapException {
	// emtpy class
};

class HeapIllegalArgument : public HeapException {
	// emtpy class
};

class HeapOutOfRange : public HeapException {
	// emtpy class
};

#endif
